
chatgpt:
  temperature: 0.7
  api-key: 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


#  twenty_two
#  api-key: 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
#  twenty
#  api-key: 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
